model: architext/gptj-162M
#checkpoints_dir: ./checkpoints/
device: cuda
seed: 42
top_p: 0.95
temp: 0.85
#timeout: 5  # Seconds
gpus: 1
max_length: 512
batch_size: 16
init_steps: 58
iterations: 1000
n_bins: 20
fp16: True
pad_token: 50256
task: "Architext"
#run_name: ???  # Mandatory string argument that describes the run.

###################################################################################################
# Hydra config overrides:
hydra:
    run:
        dir: logs/${run_name}
    sweep:
        dir: logs/${run_name}
